### ISSUE TITLE
It always tries to close an HTML comment, even if it is already closed

### ISSUE THREAD

**Issue by JeremyHeleine** [mrhanlon/less-than-slash#16]
Hi,

If an HTML comment is opened, writing `</` will close it. Of course, it's a good thing, but it prevents us from closing another tag.

For example let's assume that I wrote: `<p><!-- test`. Now, I write `</` and I obtain: `<p><!-- test -->`. Finally, I write `</` again to close the `p` tag, but I obtain: `<p><!-- test -->-->`.

Don't hesitate if you need more informations.

**Comment by MarcoThePoro** [comment]
Whoopisies, I guess I must not have tested for that, I'll check it out.

**Comment by MarcoThePoro** [comment]
I've found the issue:

`findUnclosedTags` which jumps through the text in search of tags only looks for the next `<` and skips over any `-`s or `]`s when looking for tags.
```
findUnclosedTags: (text, unclosedTags = []) ->
    unless text == ""
      if text[0] is "<"
        text = @handleNextTag text, unclosedTags
        return @findUnclosedTags text, unclosedTags
      else
        index = text.indexOf("<")
        if !!~index
          text = text.substr index
          return @findUnclosedTags text, unclosedTags
    return unclosedTags
```
I have a fix in mind and am working on it now.

**Comment by JeremyHeleine** [comment]
Wow, that was fast, thanks! And thank you for your package!
