### ISSUE TITLE
Empty tags close

### ISSUE THREAD

**Issue by mrhanlon** [mrhanlon/less-than-slash#2]
Noticed that the `input` tag was getting closed when it should be skipped because it's in emptyTags.

**Comment by aVandalInShorts** [comment]
It might be an empty tag in HTML or PHP, but with XSLT it can be oppened to change the attributes like so:

```
<input>
	<xsl:if test="$itIs = true()">
		<xsl:attribute name="value">It is</xsl:attribute>
	</xsl:if>
</input>
```

So I have to close it with the wrong closing tag and manually change it.

**Comment by MarcoThePoro** [comment]
@aVandalInShorts to get around this you can omit `input` from the `Empty tags` setting. Note this will cause `input` tags to complete in all (non XSLT) files which might be just as annoying, you could get around that by writing all your normal `input` tags as self closing (ie. `<input />`) though.
