### ISSUE TITLE
Tags closing twice

### ISSUE THREAD

**Issue by paperrobots** [mrhanlon/less-than-slash#22]
When I try to close a tag I type </  but then it does something like this:

    </a>a>

**Comment by mrhanlon** [comment]
Hmm. I'm having problems reproducing this. Can you provide some more info about your environment? Also, perhaps a larger sample that I can reproduce this with?

**Comment by paperrobots** [comment]
I'm on Atom 1.3.2, less than slash version 0.12.0. No other plugins enabled. 

I think I fixed the issue though. Restarted all the things. Seems good now.

**Comment by mrhanlon** [comment]
Interesting. Well, if it pops back up let us know. I wonder if there was something specific in your buffer that was tripping the tag parsing up.

**Comment by knightzac19** [comment]
I had this same issue where it was closing twice like that, I ended up having to uninstall and reinstall the package and the issue went away (and having to reload atom as well as said in #23). I'm wondering if it didn't update properly or an atom update messed with it? I'm on Atom 1.3.3 and latest version of the plugin.
