### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by jackmaney** [mrhanlon/less-than-slash#3]
Generated by Atom's [Deprecation Cop](https://github.com/atom/deprecation-cop):

> atom.workspaceView is no longer available.
> In most cases you will not need the view. See the Workspace docs for
> alternatives: https://atom.io/docs/api/latest/Workspace.
> If you do need the view, please use `atom.views.getView(atom.workspace)`,
> which returns an HTMLElement.
> ```
> Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
> Object.activate (/Users/jackmaney/.atom/packages/less-than-slash/lib/less-than-slash.coffee:19:9)
> ```

**Comment by mrhanlon** [comment]
Thanks, I plan to get to this this weekend!
