### ISSUE TITLE
Update Broke it - adding more end tags

### ISSUE THREAD

**Issue by dewebdesigns** [mrhanlon/less-than-slash#31]
I was using a 0.11 version before upgrading to 0.12.3. Now, when I open a blank document and type: `<a href=''></` it ends up being `<a href=''></a>a>a>` instead of closing the tag as expected.

**Comment by mrhanlon** [comment]
Can you try restarting Atom or reinstalling the package? I believe the problem is related to how the buffer listener was being attached in 0.11 versus 0.12.3. If you updated while you had open editors it would likely cause the behavior you describe.

**Comment by dewebdesigns** [comment]
Perfect. I can't believe I didn't try that. Sorry.
