### ISSUE TITLE
Completes tags when redoing

### ISSUE THREAD

**Issue by MarcoThePoro** [mrhanlon/less-than-slash#35]
If you undo a tag completion and then try to redo it, less-than-slash will insert the rest of the tag despite that the redo has already inserted the rest of the tag, resulting in something silly like `</div>div>`. What's worse is that you lose your redo history since less-than-slash inserting text is the same as typing it in yourself.

We need to find a way to ensure that the event that triggered the completion wasn't a redo

**Comment by luishdez** [comment]
Just came to report the same issue…

**Comment by MarcoThePoro** [comment]
I've just gone to try and fix this bug but now I can't even reproduce it...

@luishdez could you explain exactly what inputs you made for this to occur?

**Comment by c43** [comment]
open a new file
save as .html
in editor, type:
`<div>
</`
less-than-slash finishes the tag, great:
`<div>
</div>`

I then use cmd+Z to undo, then I have:
`<div>
<`
then cmd+shift+Z to redo, results in:
`<div>
</div>div>`

bonus:
to go further, undoing again from this point leaves you with:
`<div>
</di`
and then redoing gets you:
`<div>
</di</div>`

NOTE: This is all a rather trivial mess - easy to clean up - compared to the other _what's worse_ issue @MarcoThePoro mentioned: less-than-slash overwrites your 'redo history'

Sometimes while coding I realize I changed/deleted something that I need back the way it was. I will undo SEVERAL steps, highlight and copy the old thing, and then redo all those steps to get back to my latest code with the old snippet in my clipboard ready to inject. I know this is risky (a single accidental keystroke will also erase your redo history) but sometimes it's the only/quickest option.

**Comment by mrhanlon** [comment]
I think this is fixed with v0.18.0. Thanks!
