### ISSUE TITLE
Crashes Editor When Slash Is Added to a <br> Tag

### ISSUE THREAD

**Issue by johnmccain** [mrhanlon/less-than-slash#36]
If the "br" in a `<br>` tag is selected and then replaced with a backslash, the less-than-slash package will crash the editor.  This seems to happen only when there is a tag to be closed.

Example:

`<h1>
    <br>`

Replacing the br in `<br>` with a slash will crash the editor.

**Comment by MarcoThePoro** [comment]
Yeah I'm able to reproduce this, will investigate.

**Comment by MarcoThePoro** [comment]
I just tested it and #24 fixes this so maybe we could just merge that and publish? @mrhanlon?

**Comment by mrhanlon** [comment]
@MarcoThePoro done!

**Comment by johnmccain** [comment]
Thanks!
