### ISSUE TITLE
Add a setting to choose cursor position after autocompletion

### ISSUE THREAD

**Issue by rnyberg** [mrhanlon/less-than-slash#37]
Hi, this is an small enhancement suggestion.

I'd like to have my cursor in front of the closing tag after auto completion, because I prefer to write both the opening and closing tag before adding code between tags.

**Comment by MarcoThePoro** [comment]
Implemented on https://github.com/mrhanlon/less-than-slash/pull/38. Just need a merge and publish @mrhanlon.
