### ISSUE TITLE
Table Issues

### ISSUE THREAD

**Issue by xtreme696** [mrhanlon/less-than-slash#41]
The "table" tag won't close after the next "</". It goes directly from "/tr" to the table parent.

**Comment by MarcoThePoro** [comment]
Could you show me a snippet of what you were editing?

I tried
```html
<section>
  <table>
    <tr><td>Table Item 1</td><td>Table Item 2</td></tr>
  </
```
and it completed with the `</table>` tag as expected.

**Comment by xtreme696** [comment]
Well.. now it's working perfectly...
This was the problematic tag:

<div id="content">
  <table id="q1" border="0" cellspacing="0" cellpadding="20">
    <tr class="question">
      <td colspan="3">“text”</td>
    </tr>
    <tr class="answer">
      <td><a href="#" class="false">text1</a></td>
      <td><a href="#" class="false">text2</a></td>
      <td><a href="#" class="true">text3</a></td>
    </tr>
  </table>
</div>

But now after the last update has been installed (0.16.0) it worked just
fine :D

Thanks for this awesome atom package!
