### ISSUE TITLE
PHP Short Echo Tags

### ISSUE THREAD

**Issue by entozoon** [mrhanlon/less-than-slash#44]
Before I start: love the plugin, super useful!
Is it possible to add an empty tag rule in settings to stop it trying to autocomplete the short open tags that all the cool kids are using these days? i.e.
`
<div><?=$content?></
`
Auto closes to:
`
<div><?=$content?></?=$content?>
`

I tried adding `?=` in settings but I can see why that didn't work :)

**Comment by MarcoThePoro** [comment]
What exactly is the syntax for the type of tag you're using? 
Do you just need it to ignore tags that start with `?=`?

**Comment by entozoon** [comment]
Yeah I think that's right. If the previous tag started with `<?=`, don't bother trying to close it

**Comment by MarcoThePoro** [comment]
Do they always end in `?>` or just `>`?

**Comment by entozoon** [comment]
Always `?>`

**Comment by MarcoThePoro** [comment]
Ok here is a very brittle temporary solution, kind of a preview of the custom parsers feature.
Put this code into your init script. It will register a custom parser that simply skips any `<?= ?>` tag.
This could break with any update, but I plan on releasing an "official" way of doing this soon. This is just a hack.

```coffeescript
subscription = atom.packages.onDidActivatePackage (pkg) ->
  if pkg.name is "less-than-slash"
    pkg.mainModule.parsers.unshift {
      name: "<?="
      trigger: null
      test: /^<\?=.*?\?>/
      parse: (text) ->
        {
          type: @name
          selfClosing: true
          length: text.match(@test)[0].length
        }
      getPair: null
    }
    console.warn "Activated hack less-than-slash parser for <?= ?> tags. This could break at any time"
```

**Comment by MarcoThePoro** [comment]
@entozoon tell me if it works for you

**Comment by entozoon** [comment]
Dude that's 110% perfect, I'll close the issue and look forward to the new feature update :)
Thanks so much, made my life a lot easier!
