### ISSUE TITLE
Closing the tag no longer indents back

### ISSUE THREAD

**Issue by LuisRodriguezLD** [mrhanlon/less-than-slash#54]
Whenever I closed a tag the line would auto indent back, not sure if this is an Atom thing o a less-than-slash thing.

This is how it used to be: Seen in example gif as well.
```
<h1>
    <p>
        <a>
        </a>
```

This is what it does now:
```
<h1>
    <p>
        <a>
            </a>
```

**Comment by urbanjaklin** [comment]
I'm having the same issue.. not sure what caused the sudden change, but mine also started having this odd behavior a day or two ago

**Comment by MarcoThePoro** [comment]
Hi, I'm able to reproduce the indenting bug and am investigating, but @urbanjaklin the return cursor option still seems to be working for me, you've got it enabled and you're not in suggest mode right?

**Comment by MarcoThePoro** [comment]
Opened a PR for a fix to this issue, still not sure about why the return cursor option wasn't working for you @urbanjaklin but the new code should be more consistent about dealing with that option, hopefully fixes the issue for you 😃

**Comment by urbanjaklin** [comment]
Hey @MarcoThePoro thanks for the fix! I'll have to wait to check on it once I'm back at work, as it's the only machine I use atom on. It may be the setting/option, as you've mentioned!

**Comment by LuisRodriguezLD** [comment]
thank you very much @MarcoThePoro !!

**Comment by MarcoThePoro** [comment]
Appears to be working as of 0.18.0 🎉
