### ISSUE TITLE
Immediate completion mode breaks the undo grouping interval

### ISSUE THREAD

**Issue by JonGarbayo** [mrhanlon/less-than-slash#57]
Hi @mrhanlon!

A little issue with your package: on immediate completion mode, it breaks the native "Undo Grouping Interval" of Atom.
You can find the relative settings in Settings > Editor > Undo Grouping Interval.

It's like this interval was set to 0, ignoring the provided value: when you undo, it removes only one character at a time, which could be veeeeeeery long in some cases :/

Atom 1.23.3
Windows 10 ver. 1709 and Ubuntu 16.04 with latest updates
less-than-slash 0.18.0

**Comment by MarcoThePoro** [comment]
I can reproduce, working on a fix.
