### ISSUE TITLE
Extremely poor performance 

### ISSUE THREAD

**Issue by aminya** [mrhanlon/less-than-slash#61]
The owner of @atom-community here. This package destroys Atom performance when you type. Please remove the feature that causes this until the issue is fixed. 

If you don't maintain this package anymore, please make the package empty, register a new version (so the current users upgrade to it), and then unpublish it. Atom users think that the issue is Atom itself, while it is this package.

I have attached the CPU profile:
[CPU-20210207T150604.zip](https://github.com/mrhanlon/less-than-slash/files/5940003/CPU-20210207T150604.zip)

![image](https://user-images.githubusercontent.com/16418197/107163566-c60d9f80-696f-11eb-91fd-892b006827c3.png)

@mrhanlon

**Comment by mrhanlon** [comment]
@MarcPorciuncula Not sure if you're still maintaining this. If not I can deprecate the package.

**Comment by aminya** [comment]
Please make the package empty before deprecating in a major version change. This fixes Atom for the current installers of this package.

**Comment by MarcPorciuncula** [comment]
@mrhanlon I've moved on to VSCode so feel free to deprecate. Thanks

**Comment by aminya** [comment]
I made a PR deprecating the package: https://github.com/mrhanlon/less-than-slash/pull/62

You just need to run `apm publish minor` after mering it.

**Comment by mrhanlon** [comment]
PR merged and version 0.20.0 published. Thanks!

**Comment by aminya** [comment]
Thank you! I will make sure to add it to the list of deprecated packages.
