### ISSUE TITLE
Interest in helping to maintain less-than-slash

### ISSUE THREAD

**Issue by jllamas** [mrhanlon/less-than-slash#63]
Hey @mrhanlon,

I love this package already miss it! I would like to help maintain it.

Cheers,
Jacob

**Comment by mrhanlon** [comment]
@jllamas, great! To start, I will invite you as a collaborator on the project.

I'm not really sure where to start as far as updating the package for better performance on large files. There are a few performance-related issues open and closed that probably provide some pointers as far as where to start. I wouldn't be surprised if a near-total rewrite would be required. I haven't been keeping up with the development of Atom for a while, and it has certainly moved FAR beyond the early days of coffeescript,  which was the state of things when I initially wrote this.

**Comment by jllamas** [comment]
Thank you so much, I'll start poking around.

**Comment by weareindi** [comment]
Hi @jllamas - I'd like to help.
